### ISSUE TITLE
Condense material monsters

### ISSUE THREAD

**Issue by PeteAndersen** [swarfarm/swarfarm#10]
HasteBro:
> The idea is to make monsters like Rainbowmons, Devilmons and Angelmons "condensed" into a single line in the list view (and maybe box view). This could also extend to monsters marked as fodder.
> The "condensed" entry would show the amount of that material monster over the image, much like how the "skill-ups remaining" do with Devilmons (maybe when on mouse over).

https://swarfarm.com/feedback/454/

**Comment by QuatZo** [comment]
Shouldn't it be closed since there's already Material Storage?

**Comment by PeteAndersen** [comment]
Yeah, I am OK with closing this now that material storage exists.
