### ISSUE TITLE
Opinionated Rune Rating

### ISSUE THREAD

**Issue by claytondaley** [swarfarm/swarfarm#100]
While Efficiency and Max Efficiency are available for runes, I've never felt like they were terribly useful:

- Efficiency increases (and Max Efficiency decreases) as runes are leveled so these metrics are only reliable when comparing runes of equal level.
- Both metrics treat flat (HP/DEF/ATK) stats and % stats as equally valuable even though flat stats are never as valuable for 6* (and the vast majority of 5*) mons.
- Neither accounts for the (usually higher) strategic value of SPD
- Neither accounts for the fact that some stats are very rarely useful together (e.g. ACC and RES)
- Neither accounts for stat-set fits

I'd like to add a metric to the rune screens that addresses at least several of these issues.  I describe the metric as "opinionated" because some of the relative values (e.g. % vs flat) will need to be averages/approximations based on judgement.

Some early discussion of a very narrow/specific metric can be found [on Reddit](https://www.reddit.com/r/summonerswar/comments/aplc1y/keepingupgrading_runes_a_value_formula/), but I'd like to develop a more general/sophisticated version of this formula that could be used e.g. to prioritize rune upgrades.

Like the "planner" code in #80, I need to develop this for my rune optimization code.  However, the algorithm should be useful on its own so I'd like to expose it somewhere -- maybe the rune list screen.

**Comment by PeteAndersen** [comment]
I'm fine with a different rune rating metric as long as there is buy-in from the majority of the community.

**Comment by claytondaley** [comment]
I'm going to close this out in favor of #107 (with support for SWOP-style weights).

**Comment by claytondaley** [comment]
I think there's additional improvements to be made, but #107 is the 90% so I'll reopen a ticket proposing more specific improvements as I work them out.
