### ISSUE TITLE
Not receiving an email with password reset

### ISSUE THREAD

**Issue by Sinnersslayer** [swarfarm/swarfarm#101]
Hi,
I have recently came back to the game and wanted to access my account and seems like my password is not working so I have clicked the link for the reset, it said the email address is valid and it sends me a reset link but I never got it.
It isn't in my Spam folder.
Tried couple of times.

**Comment by Xzandro** [comment]
SWARFARM recently lost all server data due to some issues with the previous donated servers (as you can read on the start page of SWARFARM). So, you probably have to create a new account in the first place if you didn't create one after the  Jan. 31, 2019.

**Comment by Sinnersslayer** [comment]
I didn't.
So all my data is alost including by team setups :(
Oh well.
Gotta start from the scratch :)
Thanks :+1:
