### ISSUE TITLE
Error Login

### ISSUE THREAD

**Issue by bubba9514** [swarfarm/swarfarm#103]
Forbidden (403)
CSRF verification failed. Request aborted.

More information is available with DEBUG=True.

**Comment by PeteAndersen** [comment]
Please provide more information

**Comment by bubba9514** [comment]
When I go to login it brings me to this error

**Comment by PeteAndersen** [comment]
Clear your cookies and try again

**Comment by bubba9514** [comment]
Tried that and still didnt work

**Comment by PeteAndersen** [comment]
I'm sorry, I do not see any issues on my end.
