### ISSUE TITLE
Com2us data

### ISSUE THREAD

**Issue by nimaen** [swarfarm/swarfarm#111]
Hey there :)
I was just wondering where you have found the localvalue.dat file, which allow you to generate the bestiary if I'm correct ?
I've been searching for a day without a clue :D
It would be nice if you could share this tip 🙏 👼

**Comment by PeteAndersen** [comment]
It requires rooted access on an Android device. In my specific case (an old version of Nox emulator) the files are located in `/data/data/com.com2us.smon.normal.freefull.google.kr.android.common/`.

**Comment by nimaen** [comment]
Thanks a lot !
I missed the root part 😉
