### ISSUE TITLE
New dimensional hole update broke importing

### ISSUE THREAD

**Issue by japurillo** [swarfarm/swarfarm#112]
Using SWexporter, I am getting this issue with the new runes and what not:

![Screen Shot 2019-06-13 at 8 09 34 PM](https://user-images.githubusercontent.com/5369389/59455251-5f587b80-8e46-11e9-9881-034ed757a65e.png)

**Comment by PeteAndersen** [comment]
I'm very aware of the issues due to the update, it will be some time before I can get everything updated to match what Com2US has changed. Please do not raise any more issues on this.
