### ISSUE TITLE
Add 'fusion from' to monsters

### ISSUE THREAD

**Issue by Koopabro** [swarfarm/swarfarm#113]
I think it would be really nice if you could see what monsters are needed for a fusion monster on the overview page.

**Comment by PeteAndersen** [comment]
Which page are you referring to when you say overview page?

**Comment by Koopabro** [comment]
I meant on the bestiary pages (such as https://swarfarm.com/bestiary/14501-water-phoenix-sigmarus/).

**Comment by Koopabro** [comment]
![image](https://user-images.githubusercontent.com/7326459/63998705-05408b80-cb02-11e9-8e3f-d1aff688d416.png)

I made a mockup (I guess you would use the monster icons).

**Comment by deirdresm** [comment]
On that page, I think it'd be better grouped with the Fusion Ingredient For: section further down the page. OTOH, I think section's too far down the page; it should be above the fold, as it were.

**Comment by deirdresm** [comment]
So unless I missed it, there's no column for a monster being fused from other monsters, only for the reverse case.

This query does give the names of the monsters in question. Just wanted to prototype the sql before trying to see how to implement it in code.

select fuse_to.name, fuse_from.name from bestiary_monster fuse_to, 
	bestiary_monster fuse_from, bestiary_fusion bf, 
	bestiary_fusion_ingredients bfi 
	where fuse_to.id = bf.product_id 
	and fuse_from.id = bfi.monster_id
	and bf.id = bfi.fusion_id
	order by fuse_to.name, fuse_from.name;

**Comment by PeteAndersen** [comment]
Luckily Django provides a reverse relationship to the Fusion model from any instance of a Monster. You can access all the ingredients like so:

```
from bestiary.models import Monster
>>> m = Monster.objects.get(com2us_id=14501)  # water phoenix
>>> print(m.product.first().ingredients.all())
<QuerySet [<Monster: Arang>, <Monster: Jojo>, <Monster: Mina>, <Monster: Susano>]>
```

**Comment by deirdresm** [comment]
Awesome, thank you! I'll work on a pull request for this.

**Comment by deirdresm** [comment]
I submitted a pull request for this, but it's apparently not quite done.

The side effect is that if you're looking at a monster in your inventory that was a fusion, here's what it shows:

<img width="479" alt="Screen Shot 2019-12-26 at 13 46 51" src="https://user-images.githubusercontent.com/10251429/71491614-7c530b80-27e6-11ea-80e3-3e830e8f8f0c.png">

So it's showing it's a fusion…from the unawakened version of a fusion mon. I obviously missed a trick somewhere.

**Comment by PeteAndersen** [comment]
Thanks to @deirdresm for the contribution! This is now live.
