### ISSUE TITLE
Incorporate 1/4/20 balance patch pre-notice.

### ISSUE THREAD

**Issue by deirdresm** [swarfarm/swarfarm#120]
[Changes are detailed here.](https://www.withhive.com/help/notice_view/35760)

Affects the following families:

* Anubis
* Archangel
* Monkey King
* Beast Monk
* Druid
* Pioneer
* Hell Lady
* Polar Queen
* Dragon
* Valkyrja
* Cannon Girl
* Dragon Knight
* Samurai
* Neostone Agent
* Neostone Fighter
* Rakshasa
* Sylphid
* Gargoyle

**Comment by deirdresm** [comment]
Sorry, accidentally typed that I was working on this in this bug (instead of the other window I had open), but it's parsed from the data files we don't yet have.

**Comment by PeteAndersen** [comment]
Thanks for the heads up. I usually wait until the patch drops in order to have access to the data files so that multipliers and any stat changes are available.

**Comment by deirdresm** [comment]
Noted and will do in the future.

5.2.2 has gone live, so the patch is now dropped.

**Comment by PeteAndersen** [comment]
Changes are now live
