### ISSUE TITLE
Sort on Skills Column

### ISSUE THREAD

**Issue by claytondaley** [swarfarm/swarfarm#122]
We're having a 4* skilllup event so I wanted to find my not-fully-skilled 4* mons.  Filtering 4* was easy but I didn't see an easy way to sort/filter away fully skilled mons.  I could have gotten close if clicking on the Skills column sorted monsters by skillups needed.

**Comment by PeteAndersen** [comment]
In list view mode there is a column (hidden by default) that displays skill ups remaining and is sortable. 
![image](https://user-images.githubusercontent.com/11867035/72670448-39094880-39f2-11ea-956b-3d85e7c145a5.png)
