### ISSUE TITLE
ERROR: Error in field []: 'unit_lock_list' is a required property during import.

### ISSUE THREAD

**Issue by RaspFR** [swarfarm/swarfarm#133]
Hi Porksmash, 
When I want to import an exported swop **.json** file I have the following error : 
ERROR: Error in field []: 'unit_lock_list' is a required property
It was working up until now. Now I can't import this file on swarfarm anymore.
Can you please investiguate ? :)
Thank you !
![importError](https://user-images.githubusercontent.com/10197265/78400268-a773a500-75f6-11ea-9ac6-14cf5ebf2067.png)

**Comment by Xzandro** [comment]
This is not supported. You can't import an exported SWOP file to SWARFARM. That never worked, cause I dont save enough information in SWOP.

**Comment by PeteAndersen** [comment]
Xzandro is correct but I think there's room for improvement here. If the `unit_lock_list` is not present I can just skip over it and not change any locked status in swarfarm. For new monsters they will be created as unlocked.

**Comment by RaspFR** [comment]
can be a good trade off ;). 
Thanks for your answers guys by the way.
