### ISSUE TITLE
data log: Rune Crafting and Rift Raid show wrong HTML page title

### ISSUE THREAD

**Issue by Lyrex** [swarfarm/swarfarm#134]
For me, the endpoints under `profile/<name>/data_logs/rune_crafting/`  and `profile/<name>/data_logs/rift_raid/` shows the wrong HTML title. Instead of `Rift Raid` it says `Dungeons` and instead of `Rune Crafting` it says `Wishes`.

The expected behavior here would be that the HTML title matches the sites heading.

**Comment by PeteAndersen** [comment]
Thanks!
