### ISSUE TITLE
Unable to complete the import

### ISSUE THREAD

**Issue by mightormagic** [swarfarm/swarfarm#136]
I have not been able to complete the import for a few weeks now. It always seems stuck between parsing monsters or parsing runes.

Even if it seems finished parsing monsters, i still see a lot of duplicate monsters (for fusion etc)

You can try with my json file to see what could be the reason. Thanks

[test.zip](https://github.com/PeteAndersen/swarfarm/files/4595770/test.zip)

**Comment by deirdresm** [comment]
I haven't been active in a while (had covid) so my build is out of date and I'm catching up on things. When you say it's stuck, do you mean it usually stops processing?

**Comment by mightormagic** [comment]
it just never move past 'parsing runes', as if it is still processing. but after 30min, still on 'parsing runes'

**Comment by deirdresm** [comment]
Gotcha. I'll try to take a look later today (after updating) and see what's happening.

**Comment by PeteAndersen** [comment]
I deployed a fix for this yesterday, is it still occurring?

**Comment by mightormagic** [comment]
It works great now. Thank you so much!
