### ISSUE TITLE
Deserialization of multiplier_formula_raw

### ISSUE THREAD

**Issue by scorduan** [swarfarm/swarfarm#138]
multiplier_formula_raw is expressed as "multiplier_formula_raw": "[[\"ATK\", \"*\", 3.6, \"+\", 20]]" for skill id 162 using api v2. Initially I thought this should be considered a string. C# doesn't seem to know what to do with it off-hand. I was hoping to use it instead of implementing my own tokenization of multiplier_formula. Any hints you can give me on how this is expected to be deserialized would be great. Unfortunately, I can't seem to grasp the organization of python/django to really get a grip on what the code here is doing.

**Comment by claytondaley** [comment]
That's basically a list of tokens in stringified JSON.  The absence of quotes around the numbers cause them to be decoded as integer/float.  The only non-standard feature is the double brackets where you'd expect single bracket in JSON.

Decoding is only half the battle as you also need to process the tokens.  In theory something like [antlr](https://www.antlr.org/) is the right way to process tokens, but you'd be building a full math engine to decode some simple strings (unless you can find an [example](https://www.javahelps.com/2019/04/antlr-hello-world-arithmetic-expression.html) that already does most of what you need).  In this case, you'd actually define ATK in the grammar.  When you process the AST, you have a function that knows how to interpret that value.

The other direction is to collapse it into a string and find an existing package (maybe [this](https://beltoforion.de/article.php?a=muparserx)) that will re-parse and interpret the string.  Before you collapse the string, you walk the list and replace values like ATK.

**Comment by PeteAndersen** [comment]
`multiplier_formula_raw` is taken verbatim from the game files (hence the `raw` bit), and is not in a usable format for any math parsing library. The particularly annoying detail is that it is evaluated left-to-right and does not respect the usual order of operations. However, nested `[` `]` act as parenthesis would in normal math.

In the `multiplier_formula` field I've parsed the formula into a valid mathematical statement and have marked tokens with curly brackets and more straightforward attribute names. I'd recommend using that instead.
