### ISSUE TITLE
Summoned awakened monster displayed with one additional natural star

### ISSUE THREAD

**Issue by NacerSebtiMS** [swarfarm/swarfarm#139]
In Data Logs > Summons > Quick links > Mystical Scroll when an awakened monster is summoned it counts with an additional natural star.
As I don't have more data on the other scrolls, I can't say if only the 3* are affected or if that issue applies to the other scrolls.
![Summoned awakaned monster displayed with one additional natural star](https://user-images.githubusercontent.com/40132944/83346523-2e898480-a2eb-11ea-9f6b-c3c10e59f612.PNG)

**Comment by PeteAndersen** [comment]
Thanks - the reports were using "base stars" which is the value displayed in the in-game monster collection. Changed to the correct natural stars number which is the expected value.
