### ISSUE TITLE
Compare monsters

### ISSUE THREAD

**Issue by PeteAndersen** [swarfarm/swarfarm#14]
https://swarfarm.com/feedback/168/
https://swarfarm.com/feedback/255/ (a lot of ideas in here but monster comparisons is one of them)

>I have a new idea for a feature that would be really usefull: Comparing friend monsters. It would be great if you could compare your own monsters with that of friends.

>For example: You have a Hwa with swift/focus runes spd / atk% / atk% and your friend has Hwa with violent/focus runes spd / atk% / atk%. The comparing feature would show the difference in stats. If you are fighter rank and your friend is guardian, you could compare and see if your Hwa meets the standards for surviving in guardian.

**Comment by PeteAndersen** [comment]
I want to expand this past friends monsters and pull from the entire public profile database

**Comment by dropyghost** [comment]
I think the same, but just for friends otherwise you have some privacy issues. I would like all the members of my guild share their build with the new members to help them improve their monster.

**Comment by PeteAndersen** [comment]
I'm not so much concerned about the privacy (I'd not have linked usernames to monsters, and people have marked their profile as public already). However, the other problem is that there's just too many monsters to provide a useful direct comparison. I'm going to recycle that idea into providing stat guidelines along with common rune builds in the bestiary. 

I will implement your original idea as you've suggested it - direct comparisons among friends only.

**Comment by dropyghost** [comment]
Any update on this feature. I try to look the code to do it myself. But not sure how to read the json to get the monsters stats.

I check the code and found this line

    task = com2us_data_import.delay(data, summoner.pk, import_options)

So looks like you call an com2us api?

on the json file you cant see monster name or the runes:

 ```
"unit_id": 1501683335,
      "wizard_id": 3197512,
      "island_id": 6,
      "pos_x": 5,
      "pos_y": 7,
      "building_id": 229759096,
      "unit_master_id": 15911,
      "unit_level": 40,
      "class": 6,
      "con": 659,
      "atk": 582,
      "def": 571,
      "spd": 97,
      "resist": 15,
      "accuracy": 0,
      "critical_rate": 15,
      "critical_damage": 50,
      "experience": 1005420,
      "exp_gained": 0,
      "exp_gain_rate": 0,
      "skills": [
        [
          7301,
          7
        ],
        [
          7306,
          6
        ],
        [
          7311,
          2
        ]
      ],
      "runes": [
        {
          "rune_id": 11034281294,
          "wizard_id": 3197512,
          "occupied_type": 1,
          "occupied_id": 1501683335,
          "slot_no": 1,
          "rank": 5,
          "class": 6,
          "set_id": 3,
          "upgrade_limit": 15,
          "upgrade_curr": 15,
          "base_value": 421610,
          "sell_value": 21080,
          "pri_eff": [
            3,
            160
          ],
```
