### ISSUE TITLE
Dimension Hole results (new command, BattleDimensionHoleDungeonResult_v2)

### ISSUE THREAD

**Issue by QuatZo** [swarfarm/swarfarm#146]
With the v6.0.0 update, Com2Us changed command used for Dimension Hole Runs to v2.

**Karzhan Boss Example**
Request: https://pastebin.com/qYZeARCR
Response: https://pastebin.com/DL1eWBpz

**Comment by Lyrex** [comment]
Okay, thanks for the report! I took a quick glance over the new packet and as far as I can see, they made similar changes to it like they did on the `BattleDungeonResult_V2`.  

They now include additional information about the portal for the predator boss. Do we need those? @PeteAndersen 
If we don't then implementing the change should be pretty straight-forward since we already have the code to parse the `changed_item_list` key.

**Comment by PeteAndersen** [comment]
Don't need anything from the `portal_info` key just yet. I'm gathering a few examples for various drops and dungeon runs, practice mode, etc and will have this updated shortly

**Comment by PeteAndersen** [comment]
I actually need help with this one to get data with an ancient gem and grindstone drop. I can only reliably clear B3 on auto and the drop rate is abysmal :)

**Comment by QuatZo** [comment]
Do you need only data or data with explanation what it represents in the game? I can clear Karzhan B5 & Ellunia B5, didn't try the third one

**Comment by PeteAndersen** [comment]
Just the data is good! Enable the FullLogger plugin in SW-Exporter and send me the output from `BattleDungeonResult_V2` when a grindstone drops and when a gem drops. The data will be in `full_log.txt` in the SWEX output folder. If you don't want to attach here feel free to email directly to me swarfarm@porksmash.com. I appreciate the help.

**Comment by PeteAndersen** [comment]
Deployed updates on the live site w/ an educated guess on how the gem/grind parsing would work and it looks like I got lucky. Saw a few incoming logs with gems and grindstones. I don't keep the full data around from those logs, though, so I still need that to write unit tests to ensure future changes don't break anything.

**Comment by QuatZo** [comment]
So, I did as much runs as possible (10, no more energy), sadly only for Karzhan B5. I got grindstone only once, no Enchant Gem

Karzhan B5 - Grindstone : Blade (Rare) HP% +3-8%
https://pastebin.com/UJhWSWe6

Karzhan B5 - Rune : Rage Slot1 Legend
https://pastebin.com/Ymj00mRM

**Comment by PeteAndersen** [comment]
Tests added for the grindstone, thanks @QuatZo. Can close this out when I get an ancient gem sample which I've reached out to a few people for.

**Comment by QuatZo** [comment]
Finally got Enchanted Gem.

Karzhan B5 - Enchanted Gem : Energy (Rare) Resistance +5-10%
https://pastebin.com/eqtsYYVX
