### ISSUE TITLE
Add Minimalist Artifact Listing to Column Options for Monsters

### ISSUE THREAD

**Issue by deirdresm** [swarfarm/swarfarm#149]
Right now, what I want to know are:

1. How many of my 6* monsters don't have artifacts?
2. How many of them aren't powered up to 15?
3. How many of them are the wrong sort of artifact because I threw something on early on and I need to change them?

There's no easy way to see it (in bulk) either in the game's UI or in Swarfarm's.

It'd be nice to have something like you've got for the runes, where hovering over gives more detail, but you can see it en masse for all your monsters.

FWIW, when I'm looking at this, I'm usually filtering based on 6*, so I'm looking at archetype (because some of the archetypes don't match their skillsets, why com2us why?) leader skill, skills, runes, stats. Having the artifacts next to the runes but before the stats detail would IMHO be ideal, though others may disagree.

**Comment by deirdresm** [comment]
herders/templates/herders/profile/artifacts/artifact_image_fragment.html has the existing snippet used to display the artifact symbol/quality.

Issue is that, unlike runes, the type (atk/def/hp) isn't shown in the artifact itself, but is separate text and may introduce layout issues in the table.

**Comment by QuatZo** [comment]
Artifact icon says the type and slot if you know these symbols. It may be not known by everyone, so the order may say which slot it is. We could add some conditions:
- No artifacts equipped: Empty cell
![image](https://user-images.githubusercontent.com/48104274/98251440-fe6c9e80-1f78-11eb-880f-c50fb23b132b.png)
- Left (SB10, archetype) equipped: Only one image
![image](https://user-images.githubusercontent.com/48104274/98251403-f4e33680-1f78-11eb-8ebb-0720e8751c58.png)
- Right (PB10, attribute) equipped: Left is "?" or some other symbol like **X** on white background
![image](https://user-images.githubusercontent.com/48104274/98251133-9ddd6180-1f78-11eb-8825-37222270d4e7.png)
- Both artifacts equipped:
![image](https://user-images.githubusercontent.com/48104274/98250676-0b3cc280-1f78-11eb-9be6-5b766662787d.png)

And just by hovering over the Artifact image, you would get more info in tooltip (same as runes), where main stat is be visible.

**Comment by QuatZo** [comment]
![ART](https://user-images.githubusercontent.com/48104274/98281891-ae540300-1f9d-11eb-83e6-3b963c2cbee8.png)
I've also fixed **artifact popover** not having element/archetype logo and added artifacts to **monster popover**, since these were missing
![mon](https://user-images.githubusercontent.com/48104274/98281897-af853000-1f9d-11eb-991e-0c53a2a7a03f.png)
Is it good?
