### ISSUE TITLE
Artifacts: Add at-a-glance summary of unassigned artifacts

### ISSUE THREAD

**Issue by deirdresm** [swarfarm/swarfarm#155]
The way the Com2us UI works, it defaults to hiding the artifacts not relevant to the current monster. This means that it's  easy to accumulate a bunch of, oh, dark support HP artifacts if you farm a lot, and suddenly you can run out of artifact space. Been there.

I'd like to have a small table of unassigned attribute/type artifacts by stat (just the number of them). It probably makes the most sense to put it above the artifact listing (on the artifacts page), but below the filters.

Thoughts?

**Comment by QuatZo** [comment]
I think it's unnecessary, because the counter is visible next to every group (at least should be, it's broken on live site, making fix in few mins), so all you need to do is filter by **Assigned To** field.

**Edit**
It would work wonderful with solution from issue #154
