### ISSUE TITLE
Application Keys

### ISSUE THREAD

**Issue by jamesblack** [swarfarm/swarfarm#158]
I was trying to see if I could get just the parser part of the application working. However, I can't find any reference to what the application keys are supposed to be. Is this something you are keeping close to the chest, or am I missing something super obvious?

**Comment by PeteAndersen** [comment]
Unfortunately I cannot distribute the decryption keys. I want to avoid stepping on any toes at Com2US and I was also provided the keys by someone else, so they're not mine to give.

**Comment by jamesblack** [comment]
Sounds good, thanks very much for getting back to me!
