### ISSUE TITLE
Server error in Artifact.clean() when adding an artifact

### ISSUE THREAD

**Issue by PeteAndersen** [swarfarm/swarfarm#172]
Exception: 
```
TypeError at /profile/...username.../artifacts/add/
'<' not supported between instances of 'NoneType' and 'float'
```

LOC: https://github.com/PeteAndersen/swarfarm/blob/master/bestiary/models/artifacts.py#L384

POST data:
```
slot = '1'
element = 'wind'
archetype = ''
original_quality = '3'
main_stat = '3'
level = '15'
effects_0 = '1'
effects_1 = '20'
effects_2 = '19'
effects_3 = '13'
effects_value_0 = '15'
effects_value_1 = '4'
effects_value_2 = ''
effects_value_3 = '3'
assigned_to = ...removed...
```

Error caused by effects_value_2 being skipped over in the form. This should raise a ValidationError instead so the error propagates to the form.

**Comment by QuatZo** [comment]
Fixed
![image](https://user-images.githubusercontent.com/48104274/98739587-e6967f80-23a9-11eb-8ec0-d954363ededf.png)
