### ISSUE TITLE
Feature: be able to search for runes that don't have a property

### ISSUE THREAD

**Issue by deirdresm** [swarfarm/swarfarm#174]
While [Xennial Gamer made this video](https://www.youtube.com/watch?v=bY85fCKOQ1Y) about things he'd like to see in Summoners War proper, there are two features I'd also intended to look into adding, which I'll break into two separate requests.

This one's the harder, because it needs to search main stat, innate, and substats, so that would just be a way of filtering the runes that exclude properties (probably most commonly needed are speed and crit rate).

**Comment by QuatZo** [comment]
Any idea how to implement (UI) that? I have 2 options in mind:

1. Single *Toggle button* to 'reverse' filters from Include to Exclude
![image](https://user-images.githubusercontent.com/48104274/99191170-39d24e80-276b-11eb-8ed6-fb13b291b09b.png)

2. Adding whole new column with the same fields, but these would exclude given stats from this column
![image](https://user-images.githubusercontent.com/48104274/99191206-7bfb9000-276b-11eb-8182-3314d6287e17.png)
