### ISSUE TITLE
Add Effective HP and Damage to monster page

### ISSUE THREAD

**Issue by deirdresm** [swarfarm/swarfarm#175]
While [Xennial Gamer made this video](https://www.youtube.com/watch?v=bY85fCKOQ1Y) about things he'd like to see in Summoners War proper, there are two features I'd also intended to look into adding, which I'll break into two separate requests.

EHP is calculated by a combination of HP and Defense. [It's in the spreadsheet hanging off this BJR5 reddit thread](https://www.reddit.com/r/summonerswar/comments/dzlbxk/bjr5_advanced_dmg_and_ehp_calculator/).

While we're at it, calculated damage would also be cool to add.

I was thinking this would be for the player's monster instance page, but I could see a case for Bestiary Monster also.

**Comment by QuatZo** [comment]
Damage is quite complicated, just check how many options SWOP has. IMO it has no place as a single cell, it needs whole module.
![image](https://user-images.githubusercontent.com/48104274/99191092-b153ae00-276a-11eb-9aac-721df32f2d7a.png)

EHP shouldn't be a problem to add next to HP & DEF, will check that.

**Comment by QuatZo** [comment]
Referring to my last comment, I think we shouldn't implement DMG calculator in Swarfarm. It's already really good in SWOP.

https://user-images.githubusercontent.com/48104274/106967327-443b2d80-6747-11eb-9aae-e108f75ab9a6.mp4
