### ISSUE TITLE
Monster skillups not counting Monster Shrine monsters properly

### ISSUE THREAD

**Issue by QuatZo** [swarfarm/swarfarm#187]
https://swarfarm.com/feedback/176/
> Hi, thanks for the update with monster shrine, i think there is a counting problem.
> 
> I took 2 exemples from my profile : 
> - Cow Girls : got 37 loren in monster shrine, but when i go to see skill up possible, only one skill up possible from monster shrine
> - Dice Magician : got 11 dice magician in monster shrine (4 different element), but only five skill up possible from monster shrine
>  
> Using SWEX 0.0.36 with option "Merge sealed monster storage into profile data" (tried without and then nothing was in shrine), alse tried to import with "clear entire profile on import", same result.
> 
> Thanks.

![image](https://user-images.githubusercontent.com/48104274/103465403-60f4d780-4d3b-11eb-84ea-32ac58f405bc.png)
![image](https://user-images.githubusercontent.com/48104274/103465404-64885e80-4d3b-11eb-9e01-646a880792e8.png)
![image](https://user-images.githubusercontent.com/48104274/103465406-694d1280-4d3b-11eb-98a9-26d3b5b875fb.png)
![image](https://user-images.githubusercontent.com/48104274/103465407-6c480300-4d3b-11eb-8b14-932f415052b2.png)

**Comment by Zillerfr** [comment]
Hi, thanks for looking at my feedback, if you need it, I can PM you my json file.

**Comment by QuatZo** [comment]
> Hi, thanks for looking at my feedback, if you need it, I can PM you my json file.

No problem. It's an oversight from my side. I've already reproduced it locally, working on it.
