### ISSUE TITLE
Bring bestiary/fixtures/bestiary_data.json.zip current

### ISSUE THREAD

**Issue by deirdresm** [swarfarm/swarfarm#203]
…it still doesn't have the Street Fighter units, which means swarfarm local users who can't do the unencryption themselves don't have the current data.

**Comment by QuatZo** [comment]
Fixtures haven't been updated yet, task for @PeteAndersen.

**Comment by QuatZo** [comment]
Updated https://github.com/PeteAndersen/swarfarm/commit/4c3be6ebaaa9f2b1ec8e7e3e70d07c0b69840fb8
