### ISSUE TITLE
Jultan missing reflect dmg

### ISSUE THREAD

**Issue by Sylvus** [swarfarm/swarfarm#205]
I think Jultan is missing the reflect dmg effect on his passive. Ragdoll has it, so I don't see why Jultan should not have it.

Furthermore the hover text and the API say ""description": "33% of incoming damage" but the 33% is not accurate. Camules might get close to 30% but Jultan is around 12 and Ragdoll around 15%.

**Comment by QuatZo** [comment]
I've added `Reflect Damage` to Jultan.

The thing with description is, it's an actuall buff that can be stripped. Right now it's being used for all monsters, even for passives. My proposition is to rename it:

**33%** of incoming damage is reflected back at the attacker. This does not nullify any Status Effects. -> **Part** of incoming damage is reflected back at the attacker. This does not nullify any Status Effects.

I would need @PeteAndersen opinion here.
