### ISSUE TITLE
Missing effects for skills

### ISSUE THREAD

**Issue by Sylvus** [swarfarm/swarfarm#206]
Yesterday I opened a ticket about an effect missing for Jultan. Today I checked a random skill and noticed that the effects were also missing https://swarfarm.com/api/v2/skills/?id__in=2202 - Are there a lot of these cases where the data is just missing? Does somebody has the time to go through these, or should I open issues whenever I find one?

I want to check if a monster needs accuracy on a skill, my best guess was to check for the effects via the API, but maybe there is a better way to achieve this, given that the API is not 100% accurate?

**Comment by QuatZo** [comment]
These effects are not available in game files, so we are updating them manually, based on description. Which means that we can miss some (or many) cases. Whenever you find some inconsistencies, let us know.

Also, adding an effect is not code-based task, so I prefer that you report it to us through [Feedback section in SWARFARM](https://swarfarm.com/feedback/) or directly in [Discord Dev server](https://discord.gg/EuJyvTGkxQ).
