### ISSUE TITLE
Set bonuses not taken into account

### ISSUE THREAD

**Issue by othi** [swarfarm/swarfarm#231]
Hi,

On my profile, for some reason the set bonuses are not taken into account.

My profile: https://swarfarm.com/profile/Othi. It gets auto-updated by SWEX.

For example, my Bernard is missing 25 speed from Swift (https://swarfarm.com/profile/Othi/monster/view/0c4b1377b8554f758531f938dbaef98b/), my Chandra (https://swarfarm.com/profile/Othi/monster/view/c0bc85825796445cab93525bf7e41f58/) has 0 accuracy with a focus set.

Thanks

**Comment by QuatZo** [comment]
Did you try to update your profile manually after 9th May? It may resolve the problem, for now. I'll look into live sync functionality tho.

**Comment by othi** [comment]
No, I didn't. Do you want me to try that? I can leave my profile like this if you want to investigate.

**Comment by QuatZo** [comment]
I can test it by using my own profile, so that's not a problem. The best would be if you could update it manually using newest JSON file and let me know if then everything works as intended.

**Comment by othi** [comment]
SWEX uploaded the profile again automatically and now the set bonuses are correctly taken into account. Seems it has been fixed in the meantime.

You can close the issue, thanks a lot for the quick response!

**Comment by QuatZo** [comment]
Yeah, I've pushed some import/export fixes at May 9th. Glad it resolved your problem, closing.
