### ISSUE TITLE
Add "group by monster family" to grid/monster view

### ISSUE THREAD

**Issue by rtdean** [swarfarm/swarfarm#30]
Grouping by monster/family is available in game, and I think it would be super useful here as well.  Just my $0.02

**Comment by PeteAndersen** [comment]
Is it available in game? I like the idea but I didn't know it was available in game. I only see Attribute, Level, Grade, Recent.

**Comment by rtdean** [comment]
When you are going into your Storage mode, you can group by Monster/Family.  It pulls all the members of a family right next to each other.  It's useful when you are looking at monster counts for skillups, or for fusion counts, etc.

I was using it a bunch late last week as I was looking at what 4's to 5 for the event that started on Monday.  I switched into swarfarm because I was hoping to do the same while grinding... and discovered no group-by-family... which prompted this issue.

**Comment by PeteAndersen** [comment]
Ah, I see. I could do something like this pretty quickly.

**Comment by rtdean** [comment]
It might also be useful if you are trying to decide which nat4's to sacrifice to legendary scroll pieces.

**Comment by PeteAndersen** [comment]
I really like how this turned out, thanks for the suggestion!
