### ISSUE TITLE
Skill tooltip stops working after awhile

### ISSUE THREAD

**Issue by chadleong** [swarfarm/swarfarm#34]
Any idea why the skill tooltips stops working after awhile ? It stops showing and needs a refresh,

**Comment by PeteAndersen** [comment]
Which browser and OS are you using? Any errors in the javascript console?

**Comment by chadleong** [comment]
It happens to all the browsers, PC. The error in console is Error 429:  too many requests

**Comment by PeteAndersen** [comment]
Looks like you're running into the API rate limit of 100 requests/min. I've looked into increasing this already but this is another reason to do so.

**Comment by PeteAndersen** [comment]
Bumped throttle rate by 5x for logged in users (500/min) and 10x for anonymous users (100/min)
