### ISSUE TITLE
Add com2us_id to skill api entries

### ISSUE THREAD

**Issue by rdnewman** [swarfarm/swarfarm#38]
Individual monsters records loaded via swparser include ids for the skills a given monster has to track that monster's skill level.   However, the skills api from swarfarm does not have a field that can be used to tie to the skill via that id.  It appears that the code in `swarfarm/bestiary/com2us_data_parser.py` does have some knowledge of this, if an api request (e.g., `https://swarfarm.com/api/skill/111.json`) included the relevant number, it would be easier to link the skill api record to the incoming swparser monster record.

Looks like perhaps `class MonsterSkillSerializer(serializers.HyperlinkedModelSerializer)` (in `https://github.com/porksmash/swarfarm/blob/master/api/serializers.py`) just needs to be amended?

Thanks!!

**Comment by PeteAndersen** [comment]
Live now!

**Comment by rdnewman** [comment]
Have I told you lately how awesome you are? 'Cause, porksmash, you are.
