### ISSUE TITLE
Queued for more than an hour

### ISSUE THREAD

**Issue by phyrexians** [swarfarm/swarfarm#39]
I understand that the queue system is implemented to prevent a blackout like the previous FRR a few months ago. But after queuing for the update for more than an hour, I'm beginning to think there might be a deadlock that you are facing in your queuing system. You may want to consider a maximum timeout for those updating at the front of the queue.

**Comment by PeteAndersen** [comment]
Queue process worker failed to start after a server reboot. It's processing now. Thanks for bringing it to my attention.
