### ISSUE TITLE
[suggestion] bestiary filtering by existing monster   and first skills effect

### ISSUE THREAD

**Issue by tsing80** [swarfarm/swarfarm#40]
It would be nice if bestiary list allow a checkbox in filtering options that only show the monster that the user have.

Also, it will be nice if can search only first skill effect.Such as finding monster having first skill with multiple hit effects in order to find candidate monster  for NB10

**Comment by PeteAndersen** [comment]
The first suggestion is pretty similar to what your profile monster list is. Can you explain how you'd use it in the bestiary that wouldn't work in your profile? The same filters are available in both places. 

As for your second suggestion, I have plans for a more advanced skill filter that will allow you to do that. No promises on time, though, as it requires a crapload of manual data entry first.
