### ISSUE TITLE
Filter on enchantable/gemmable runes

### ISSUE THREAD

**Issue by PeteAndersen** [swarfarm/swarfarm#41]
Add a rune filter to show or hide runes that you can use an enchant gem or grindstone on.

**Comment by QuatZo** [comment]
I'm, not sure if that's what you meant. Also, couldn't find a faster way to filter these runes out.

https://user-images.githubusercontent.com/48104274/107056131-4dbda780-67d2-11eb-83dc-b5683c93242a.mp4
