### ISSUE TITLE
Calculation error using percent runes for Lvl 40 stats

### ISSUE THREAD

**Issue by Kordau** [swarfarm/swarfarm#49]
I think I found an error in the calculation for lvl 40 stats on the individual monster stats page. I'll just use the example of what I'm seeing for my lvl 11 Kung Fu Girl...

- Base HP : **3900**
- Rune HP : **+2457** (Equipped a HP% rune with 63%)
- Current HP : **6357**
- Lvl 40 HP : **12672**

Basically, the lvl 40 stat is being calculated using _Lvl 40 base HP_ + _current bonus_ ... ie: 10215 + 2457

The Lvl 40 HP stat should actually be 16650 ... ie: 10215 x 1.63

**Comment by PeteAndersen** [comment]
Good catch. I'll update that shortly.

**Comment by PeteAndersen** [comment]
This is resolved, but requires re-saving your monsters or reimporting to see the new values.
