### ISSUE TITLE
Import not working

### ISSUE THREAD

**Issue by kolefield** [swarfarm/swarfarm#61]
I can't get past the queue (been waiting an hour now, attempted on 2 different computers; Chrome on Windows and Chrome on OSX).

`console.log(response.status, response.result);` is returning `PENDING null`, not sure if that helps.

**Comment by PeteAndersen** [comment]
See https://swarfarm.com/feedback/730/

**Comment by kolefield** [comment]
My apologies - I had not seen that section of the site. Thank you!

**Comment by PeteAndersen** [comment]
No worries, I just like to keep the discussions together so everyone can see what's going on. If you notice any site issues in the future feel free to raise them here!
