### ISSUE TITLE
Substat filter breaks when page is too small

### ISSUE THREAD

**Issue by msteudel** [swarfarm/swarfarm#62]
OS: Mac OSX 10.12.5
Browser: Firefox 53

When browser is too small, the substat drop down on the runes page doesn't work. You can see something when the gap between the input and the one or more|all toggle changes is when it starts working.

Screencast: https://screencast.com/t/SF92jfU8fX

Repro:
1. Go to runes page: https://swarfarm.com/profile/Miles00001/runes/
2. Open filter panel
3. Click in substat  input
4. If it works, slow shrink browser to the gap between the infpu and the toggle gets smaller
5. Click in substat input
6. Drop down doesn't work

**Comment by PeteAndersen** [comment]
Thanks for the report!
