### ISSUE TITLE
Essence Dungeons Charts don't show chance of size/element

### ISSUE THREAD

**Issue by Skibisky** [swarfarm/swarfarm#66]
The charts displayed for essences in the Elemental Dungeons factor in the amount of essence dropped.

For the data below, I get the following chart. Note 1 Water Low drop vs 2 Water Mids.
![image](https://user-images.githubusercontent.com/17957029/31174425-13189834-a93e-11e7-9aee-49698eb25264.png)
![image](https://user-images.githubusercontent.com/17957029/31174488-3ff2d996-a93e-11e7-947d-2a5e2e9b1536.png)
Additionally in this data, mids dropped more often than lows, but because more total lows dropped, they get more chart.

Changing drop_count to Count('pk') in the following line:

https://github.com/PeteAndersen/swarfarm/blob/a3cd9656f9a989bad26376c27269b6a22b2aa520/sw_parser/views.py#L1098

I get a chart with percentages I would expect:
![image](https://user-images.githubusercontent.com/17957029/31174515-4b021216-a93e-11e7-95d3-4af4b3f96897.png)

As it currently stands, levels that drop *more* mids per drop will have an equal chart size as levels that drop mids more often.  
My instinct was that the charts showed the percentage likeliness of a drop of lows/mids (regardless of how many dropped) and that the "Per Run" column would factor in the average amount dropped.

**Comment by PeteAndersen** [comment]
I feel that it would be misleading to classify a higher frequency of dropping as 'more' in the chart. The goal is to represent where you can get the most essences per run, which is accurately represented by quantity, not frequency. 

Drop frequency could be added as a different chart, but I would like quantity chart to remain the main focus of the reports.

**Comment by Skibisky** [comment]
Yeah, that's fair enough. I though that's what the "Per Run" column was though.

I've thrown some more columns into the table, how's it look?

![image](https://user-images.githubusercontent.com/17957029/31361977-b793c7e6-ad88-11e7-8b7e-a44f85df99a2.png)

The reason I am looking for % drop rather than % makeup is, sometimes I am 1 or 2 mids away from away from awakening a mon I don't really care where I'm going to get the most per run, I just want the least time until any drop.

A contrived example would be, where would you rather farm for 2 mids?
 - A: 30% chance of 1 mid
 - B: 10% chance of 3 mids

The current charts and numbers will have these appear equal, but if the number of runs to do to have a 90% chance of at least 1 drop is 7 for A and 22 for B. Even looking for 2 mids would be around 12 runs of A.

**Comment by PeteAndersen** [comment]
I like it. The Per Run column is `drop_chance * avg_per_drop` and giving those numbers in the report is nice. Do you want to submit a PR with those changes?

**Comment by PeteAndersen** [comment]
Closed with #68
