### ISSUE TITLE
Dungeon "mana per energy" formula is bugged/wrong

### ISSUE THREAD

**Issue by qp0n** [swarfarm/swarfarm#73]
Was comparing Necro to Dragons mana returns when the numbers didn't seem to pass the eye test. Took my calculator to do it by hand and it was way off. 

Turns out the formula is ADDING the energy returned from the run to the original energy cost, instead of SUBTRACTING it.

______________________________

example: 

- Necropolis costs 8 energy to run, returns 1.01 energy on average, average energy cost = **6.99 energy used**

- Mana drops + average rune mana =  3,892.45 + 13,623.48 = **17,515.93 mana gained**

- Mana per energy = **17,515.93 / 6.99 = 2,505.86 mana per energy**

however...

- The Necro b10 "mana per energy" on the site reads **1,944 mana per energy**

______________________________

That's when I tried to nail down what the incorrect variable was, and it turns out that 1,944 = 17,515.93 / **9.01**

... so apparently the site's formula is adding an extra energy cost, when it should be subtracting it.

**Comment by PeteAndersen** [comment]
Your example doesn't include rune drop chance. Although average rune value when dropped is 13623.48 mana, you only get a rune 71.3% of the time. That's an average of 9713.54 mana from runes, and total average mana per run is 13606. 

13606 / 6.99 = 1946 mana per energy. I can't explain the 2 mana difference from the current value in the report, but I'll look into it.

**Comment by PeteAndersen** [comment]
For posterity this is how it's calculated currently:

```python
energy_spent = energy_cost - avg_energy_dropped
mana_efficiency = (avg_mana_dropped + rune_value * rune_drop_rate) / energy_spent
```

**Comment by qp0n** [comment]
You're right, I overlooked the drop chance. Guess it was just a flukey coincidence that when assuming a 100% drop chance the calcs happened to return _exactly_ a -200% change in energy return

**Comment by PeteAndersen** [comment]
I appreciate the auditing, always good to have more eyes looking at my math
