### ISSUE TITLE
Patch 3.8.8 to present

### ISSUE THREAD

**Issue by futrtrubl** [swarfarm/swarfarm#74]
Could we get a new time filter option for the data logs "Patch 3.8.8 to present" since they changed drop rates in the higher rune dungeons in that patch?

**Comment by PeteAndersen** [comment]
I've already added this a couple days ago with d9691ee. You might have to select it from the list. 
![](https://i.imgur.com/AWnAuYA.png)

**Comment by futrtrubl** [comment]
I see it now, but I had to delete cookies for the site before it would show me the new options, with the previous "... to present" option failing to do anything.

**Comment by futrtrubl** [comment]
Nope, broken again for me. After initially seeing the new option and selecting it, it now shows the old options again.
![untitled-1](https://user-images.githubusercontent.com/5351740/42542000-678aef40-846a-11e8-9a8c-0c7891e0fa10.png)

**Comment by PeteAndersen** [comment]
This should be resolved now. Sorry, should have reopened the issue earlier, but I'll leave it for now.
