### ISSUE TITLE
Average Rune Efficiency stat on monsters doesn't reset to zero if you re-import a monster after removing all of the runes

### ISSUE THREAD

**Issue by jake-griffin** [swarfarm/swarfarm#78]
I had put a bunch of leftover runes onto a few monsters to free up monster storage. Then Com2us bumped the storage to 700 runes, so on FRR day, I removed the runes from them. I just noticed that these monsters are listing has having non-zero rune efficiency (between 39 and 60%). As an example, see my Karakum: https://swarfarm.com/profile/jako7286/monster/view/aa775e853e764844bee46138e345c472/

**Comment by PeteAndersen** [comment]
Thanks, I'll look into it

**Comment by jake-griffin** [comment]
Hm... my Karakum is showing as 0% now. Did it get updated somehow since I posted this?

**Comment by jake-griffin** [comment]
Looks like some of them are still bugged, like my Michelle:
https://swarfarm.com/profile/jako7286/monster/view/224f66f787214c92850e282a22a5eb6b/

**Comment by PeteAndersen** [comment]
Yeah, I had re-saved your Kakarum manually to see if his rune efficiency would correctly update to 0% to check a suspicion. I'm trying to reproduce locally now

**Comment by jake-griffin** [comment]
Oh, ok cool. Thanks for looking into this! Love this app by the way!
