### ISSUE TITLE
Handle inconsistencies/mistakes in data when parsing files

### ISSUE THREAD

**Issue by PeteAndersen** [swarfarm/swarfarm#82]
Need to add special handling of many inconsistencies in monster skill data.

### Number of Hits

Reported in game data files as 1 hit, but are actually:
- Kungen 3 - 5912 - 3 hits
- Liesel 3 - 6511 - 3 hits
- Lindermen 3 - 1913 - 3 hits
- dice magician S1 - 12105, 12104, 12103, 12102, 12101 - 2 hits
- xiao chun 2 - 8112 - 2 hits
- Rasheed 3 - 6715 - 3 hits
- Drunken Master S2 (dark, fire) - 8110, 8107 - 3 hits
- Viking S2 (water, light) - 5406, 5409 - 3 hits
- Ignicus 3 - 10312 - 3 hits
- Gildong 3 - 9211 - 4 hits
- Hwahee 3 - 9112 - 6 hits (random target)
- tien qin 3 - 8114 - 3 hits
- Loque 3 - 3315 - 5 hits
- Huan 3 - 8113 - 3 hits
- Gunpyeong 3 - 9212 - 3 hits
- Paladin S2 (water, dark) - 12506, 12510 - 2 hits
- Argen 3 - 6513
- Hellea 2 - 1610, 1606 - 2 hits
- Gina 3 - 7315 - 4 hits
- Okeanos 3 - 10512 - 4-6 hits
- Ellin 3 - 5811 - 4 hits
- Taoist S2 (fire, wind, light) - 9209, 9208, 9297 - 2 hits

**Comment by ageh** [comment]
Hi, I got *a few* more errors/inconsistencies.

# These should be AOE
12712
12609
11906
11907
11910
7106
7107
7109
7915
2308
2310
12808

---

# These have the wrong number of hits

10508, 10506, 10509 (Sea Emperor S2) has 2 hit(s) listed but should be 1 

5811 (Ellin S3) has 1 hit(s) listed but should be 4
10312 (Ignicus S3) has 1 hit(s) listed but should be 3
12101 (Reno S1) has 1 hit(s) listed but should be 2
12102 (Ludo S1) has 1 hit(s) listed but should be 2
12103 (Morris S1) has 1 hit(s) listed but should be 2
12104 (Tablo S1) has 1 hit(s) listed but should be 2
12105 (Monte S1) has 1 hit(s) listed but should be 2
8112 (Xiao Chun S3) has 1 hit(s) listed but should be 2
8113 (Huan S3) has 1 hit(s) listed but should be 3
8114 (Tien Qin S3) has 1 hit(s) listed but should be 3
1612 (Lucasha S3) has 1 hit(s) listed but should be 6
3312 (Fairo S3) has 1 hit(s) listed but should be 2
3315 (Loque S3) has 1 hit(s) listed but should be 5
8211 (Xiao Lin S3) has 1 hit(s) listed but should be 4
8212 (Hong Hua S3) has 1 hit(s) listed but should be 4
8213 (Ling Ling S3) has 1 hit(s) listed but should be 4
8214 (Liu Mei S3) has 1 hit(s) listed but should be 4
6812 (Cassandra S3) has 1 hit(s) listed but should be 2
7315 (Gina S3) has 1 hit(s) listed but should be 4
10913 (Olivia S3) has 1 hit(s) listed but should be 2
4814 (Gin S3) has 1 hit(s) listed but should be 2
4810 (Han S2) has 1 hit(s) listed but should be 2
4815 (Han S3) has 1 hit(s) listed but should be 3
12506 (Josephine S2) has 1 hit(s) listed but should be 2
9407 (Chiwu S2) has 1 hit(s) listed but should be 2
9211 (Gildong S3) has 1 hit(s) listed but should be 4
9207 (Gunpyeong S2) has 1 hit(s) listed but should be 2
9212 (Gunpyeong S3) has 1 hit(s) listed but should be 3
9208 (Woochi S2) has 1 hit(s) listed but should be 2
5614 (Eshir S3) has 1 hit(s) listed but should be 4
8215 (Fei S3) has 1 hit(s) listed but should be 4
5915 (Haken S3) has 1 hit(s) listed but should be 2
7406 (Fedora S2) has 1 hit(s) listed but should be 2
10613 (Lupinus S3) has 1 hit(s) listed but should be 2
5611 (Vigor S3) has 1 hit(s) listed but should be 3
4813 (Orochi S3) has 1 hit(s) listed but should be 6

---

# Those are inconsistent:
Skills that don't actually hit an enemy should have 0 hits
OR all skills that do something X times should have X hits
For example healing skills sometimes have 1 or 0 hits.
Some passives sometimes have a hit listed, others not.

Com2us ID|Monster name + skill|Hits listed in swarfarm|multiplier
:-:|:-:|:-:|:-:|
13113|Odin S3|1|None|
11211|Avaris S3|1|None|
11214|Amarna S3|1|None|
6311|Ariel S3|1|None|
6312|Velajuel S3|1|None|
6313|Eladriel S3|0|(TARGET_MAX_HP * 1.0 FIXED)|
6314|Artamiel S3|1|None|
6315|Fermion S3|1|None|
10712|Lexy S3|1|None|
5911|Gruda S3|1|None|
9311|Gangchun S3|1|None|
9312|Nangrim S3|1|None|
8307|Kumar S2|0|(MAX_HP * 0.4 FIXED)|
8308|Ritesh S2|0|(MAX_HP * 0.4 FIXED)|
8309|Shazam S2|0|(MAX_HP * 0.4 FIXED)|
12711|Sabrina S3|1|None|
12715|Martina S3|1|None|
7011|Wayne S3|1|None|
7012|Randy S3|1|None|
7015|Jamie S3|1|None|
8811|Orion S3|1|None|
8812|Draco S3|1|None|
8814|Gemini S3|1|None|
12612|Shaina S3|1|None|
12614|Deva S3|1|None|
10311|Aqcus S3|1|None|
10313|Zephicus S3|1|None|
10314|Rumicus S3|1|None|
4210|Zeratu S2|0|(ATK * 3.5)|
4215|Zeratu S3|1|None|
7411|Fedora S3|1|None|
7413|Briand S3|1|None|
11313|Hathor S3|1|None|
11314|Isis S3|1|None|
11315|Nephthys S3|1|None|
12112|Ludo S3|1|None|
12113|Morris S3|1|None|
12114|Tablo S3|1|None|
12115|Monte S3|0|(DICE_MIN * 15.0 + 10.0)|
2913|Jamire S3|1|None|
2909|Zerath S2|0|(TARGET_CUR_HP * 0.15)|
7811|Chow S3|1|None|
7813|Leo S3|1|None|
7814|Jager S3|1|None|
7815|Ragdoll S3|1|None|
12921|Abellio S3|1|None|
12936|Abellio S4|1|None|
12937|Bellenus S4|1|None|
12923|Taranys S3|1|None|
12938|Taranys S4|1|None|
12939|Valantis S4|1|None|
12925|Pater S3|1|None|
12940|Pater S4|1|None|
12806|Herne S2|1|None|
12807|Nisha S2|1|None|
12813|Mellia S3|1|None|
12809|Felleria S2|1|None|
12814|Felleria S3|1|None|
1712|Bremis S3|1|None|
1714|Priz S3|1|None|
1715|Camules S3|1|None|
11713|Erwin S3|1|None|
6706|Rina S2|1|None|
6711|Rina S3|1|None|
6707|Chloe S2|1|None|
6712|Chloe S3|1|None|
6709|Iona S2|1|None|
1106|Elucia S2|0|(ATK * 4)|
1108|Aeilene S2|0|(ATK * 4)|
1109|Neal S2|0|(ATK * 4)|
1114|Neal S3|1|None|
11911|Psamathe S3|1|None|
9909|Fran S2|0|(ATK * 4)|
11611|Tractor S3|1|None|
11613|Crane S3|1|None|
11615|Crawler S3|1|None|
1911|Konamiya S3|1|None|
1912|Cahule S3|1|None|
1914|Teon S3|1|None|
1915|Rizak S3|1|None|
13012|Vidurr S3|1|None|
13013|Skogul S3|1|None|
13015|Trasar S3|1|None|
2413|Ragion S3|1|None|
2414|Groggo S3|1|None|
2415|Maggi S3|1|None|
2513|Bernard S3|1|None|
2514|Shamann S3|1|None|
11807|Racuni S2|1|None|
11813|Raviti S3|0|(DEF * 2.5)|
11809|Dova S2|1|None|
12212|Harmonia S3|0|(15.0% FIXED)|
3412|Colleen S3|1|None|
9015|Craka S3|0|(TARGET_MAX_HP * 0.3 FIXED)|
1513|Gamir S3|1|None|
1515|Shumar S3|1|None|
3112|Kahli S3|1|None|
10114000|Homunculus(Attack) S4|1|None|
10124000|Homunculus(Attack) S4|1|None|
10134000|Homunculus(Attack) S4|1|None|
10244000|Homunculus(Support) S4|1|None|
10254000|Homunculus(Support) S4|1|None|
11411|Qebehsenuef S3|1|None|
11413|Imesety S3|1|None|
11414|Wedjat S3|1|None|
11415|Amduat S3|1|None|
4606|Lulu S2|0|(TARGET_MAX_HP * 0.15)|
4611|Lulu S3|1|None|
4607|Lala S2|0|(TARGET_MAX_HP * 0.15)|
4608|Chichi S2|0|(TARGET_MAX_HP * 0.15)|
4609|Shushu S2|0|(TARGET_MAX_HP * 0.15)|
4614|Shushu S3|1|None|
4610|Chacha S2|0|(TARGET_MAX_HP * 0.15)|
10012|Theomars S3|1|None|
10014|Elsharion S3|1|None|
1215|Garok S3|1|None|
3313|Pigma S3|1|None|
2715|Drogan S3|1|None|
2014|Belladeon S3|1|None|
11511|Chilling S3|1|None|
11513|Windy S3|1|None|
11514|Misty S3|1|None|
11515|Dusky S3|1|None|
4711|Sian S3|1|None|
7511|Rigel S3|1|None|
7512|Antares S3|1|None|
7513|Fuco S3|1|None|
7514|Halphas S3|1|None|
7515|Grego S3|1|None|
13106|Bolverk S2|1|None|
13107|Baleygr S2|1|None|
13108|Odin S2|1|None|
13109|Geldnir S2|1|None|
13114|Geldnir S3|1|None|
13110|Herteit S2|1|None|
7711|Nickel S3|1|None|
7712|Iron S3|1|None|
8714|Glinodon S3|1|None|
10612|Astar S3|1|None|
6813|Ardella S3|1|None|
11011|Luan S3|0|(MAX_HP * 0.15)|
11012|Sin S3|1|None|
6111|Mina S3|1|None|
6113|Naomi S3|1|None|
6114|Xiao Ling S3|1|None|
10406|Tetra S2|0|(ATTACK_LV * 130.0)|
10411|Tetra S3|1|None|
10417|Cichlid S2|0|(MAX_HP * 0.2)|
10409|Molly S2|0|(ATTACK_LV * 130.0)|
10414|Molly S3|1|None|
10415|Betta S3|1|None|
8613|Eintau S3|1|None|
8615|Kamatau S3|1|None|
7912|Mei Hou Wang S3|1|None|
7913|Xing Zhe S3|1|None|
11111|Nubia S3|1|None|
11113|Namib S3|1|None|
11114|Sahara S3|1|None|
7306|Megan S2|0|(ATK * 5.3)|
7311|Megan S3|1|None|
7312|Rebecca S3|1|None|
7313|Silia S3|0|(ATK * 7.3)|
7310|Gina S2|0|(ATK * 5.3)|
10914|Illianna S3|1|None|
10814|Lucas S3|0|(ATK_SHIELD FIXED) + (ATK_RUNE_SHIELD FIXED) * (0.35 FIXED)|
2214|Chamie S3|1|None|
4812|Garo S3|1|None|
7206|Anavel S2|0|(ATK * 3.2)|
7210|Nicki S2|0|(ATK * 3.2)|
7111|Praha S3|1|None|
7112|Juno S3|1|None|
7114|Laima S3|1|None|
12511|Josephine S3|1|None|
12507|Ophilia S2|1|None|
12512|Ophilia S3|0|(MAX_HP * 0.2)|
12508|Louise S2|1|None|
12509|Jeanne S2|1|None|
12515|Leona S3|1|None|
12013|Feng Yan S3|0|(DEF * 1.6)|
9512|Naki S3|1|None|
9508|Mav S2|0|(MAX_HP * 0.25)|
9513|Mav S3|1|None|
9514|Dona S3|1|None|
9510|Kuna S2|0|(MAX_HP * 0.25)|
5712|Jean S3|1|None|
5715|Guillaume S3|1|None|
3212|Perna S3|1|None|
3216|Jaara S3|1|None|
5515|Luna S3|0|(ATK * 7.2) + (TARGET_MAX_HP * 0.15)|
9411|Woosa S3|1|None|
9414|Nigong S3|1|None|
10221|Galleon S3|1|None|
10223|Barque S3|1|None|
1313|Shannon S3|1|None|
1314|Cheryl S3|1|None|
9707|Brandia S2|0|(ATK * 3.2)|
9709|Elenoa S2|0|(ATK * 3.2)|
9714|Elenoa S3|0|(10.0% FIXED)|
2114|Sharman S3|1|None|
10514|Pontos S3|1|None|
10515|Manannan S3|1|None|
2312|Fao S3|1|None|
2314|Elpuria S3|1|None|
9111|Mihyang S3|0|(ATK * 4.0)|
9116|Hwahee S2|0|(ATK * 2.5)|
9108|Chasun S2|0|(MAX_HP * 0.2)|
9113|Chasun S3|1|None|
9114|Yeonhong S3|0|(TARGET_MAX_HP * 0.5 FIXED)|
9117|Wolyung S2|0|(ATK * 2.5)|
99007|Super Angelmon S1|1|None|
3015|Aschubel S3|1|None|
2816|Lumirecia S3|0|(TARGET_MAX_HP * 1.0 FIXED)|
2818|Acasis S3|0|(MAX_HP * 0.2)|
2613|Delphoi S3|1|None|
12311|Amelia S3|1|None|
12316|Amelia S4|1|None|
12327|Helena S2|1|None|
12312|Helena S3|1|None|
12317|Helena S4|1|None|
12328|Diana S2|1|None|
12318|Diana S4|1|None|
12314|Eleanor S3|1|None|
12319|Eleanor S4|1|None|
12330|Alexandra S2|1|None|
12315|Alexandra S3|1|None|
12320|Alexandra S4|1|None|
6611|Allen S3|1|None|
6614|Darion S3|1|None|
6615|Jubelle S3|1|None|
6011|Camilla S3|1|None|
6012|Vanessa S3|1|None|
6014|Akroma S3|1|None|
6514|Julianne S3|1|None|
6515|Cadiz S3|1|None|
5411|Huga S3|1|None|
5412|Geoffrey S3|1|None|
5414|Jansson S3|1|None|
5415|Janssen S3|1|None|
1811|Dagora S3|1|None|
5612|Garoche S3|1|None|
5613|Shakan S3|1|None|
5609|Eshir S2|0|(TARGET_MAX_HP * 0.15 FIXED)|
1411|Kunda S3|1|None|
1412|Tantra S3|0|(MAX_HP * 0.5)|
1415|Kumae S3|1|None|
