### ISSUE TITLE
Why remove the resources links?

### ISSUE THREAD

**Issue by marioantonini** [swarfarm/swarfarm#85]
This was pretty handy, was there a logical reason to remove them?

**Comment by Xzandro** [comment]
This should describe the reasoning behind it: https://swarfarm.com/feedback/896/

**Comment by marioantonini** [comment]
I commented on the feedback area as well. I think the internal links were extremely useful, hopefully those are not a problem to maintain and can be brought back.

**Comment by PeteAndersen** [comment]
I understand the request to include the internal one - I will add that back
