### ISSUE TITLE
Upgrade Pillow

### ISSUE THREAD

**Issue by claytondaley** [swarfarm/swarfarm#87]
For some reason `pillow==4.1.0` isn't compatible with Py3.7.  At your convenience, would you mind upgrading to a newer version?  P.S. what version of Python are you running in production (so I don't use features you can't support)?

**Comment by PeteAndersen** [comment]
I am using 3.6. Pillow has gone through a major release, will have to check if it is still functional or not. In the meantime you can just update the package as you see fit - it is only used to trim a 1px white border around imported game assets and is not actually run with the Django wsgi application.
