### ISSUE TITLE
Last-updated date on summoner profiles

### ISSUE THREAD

**Issue by PeteAndersen** [swarfarm/swarfarm#9]
Update any time some action is performed so you can tell how out of date the swarfarm profile is. 

https://swarfarm.com/admin/feedback/issue/87/

**Comment by QuatZo** [comment]
Isn't it done? Unless you meant every time anything in profile changes, like runes etc.
![image](https://user-images.githubusercontent.com/48104274/103463326-d789d900-4d2b-11eb-9867-2c2aee48c8c8.png)

**Comment by PeteAndersen** [comment]
It does auto-update when saving monsters/runes/etc via signals [here](https://github.com/PeteAndersen/swarfarm/blob/master/herders/signals.py#L9) but should be updated for new objects added since then like artifacts. Also note that the signals need to be disconnected in the profile importing process [here](https://github.com/PeteAndersen/swarfarm/blob/master/herders/tasks.py#L43) to avoid spamming updates to the summoner profile.

**Comment by QuatZo** [comment]
So, we want to update date when updating these objects, right:

- [x] Runes
- [x] Monsters
- [x] Artifacts
- [x] Runes Craft (enchants/grinds)
- [x] Artifacts Craft (enchants)

Do we consider only SWEX (API) & Import update or from site too, i.e. when someone adds manually High Elemental or Rune Piece material?
